package entity;

public enum SportsCategory {
    WO,
    THIRD_CLASS_JUNIOR_SPORTSMAN,
    SECOND_CLASS_JUNIOR_SPORTSMAN,
    FIRST_CLASS_JUNIOR_SPORTSMAN,
    THIRD_CLASS_SPORTSMAN,
    SECOND_CLASS_SPORTSMAN,
    FIRST_CLASS_SPORTSMAN,
    CANDIDATE_FOR_MASTER_OF_SPORT,
    MASTER_OF_SPORT,
    MASTER_OF_SPORT_INTERNATIONAL_CLASS
}